


name: Docker build-push

on:
  push:
    
    
    

jobs:
  docker-ci:
    runs-on: ubuntu-latest
    


    steps:
      - name: Code Checkout
        uses: actions/checkout@v5


      - name: Docker Login
       # only login if its main branch otherwise its gonna fail
        #if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker build and push the image
        uses: docker/build-push-action@v5
        with:
          context: .
          # only push if its main branch otherwise its gonna fail
          push: "${{ github.ref == 'refs/heads/main' }}"
          tags: ${{ vars.DOCKER_USERNAME }}/node-js-new-app:latest


